import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font.normal]
family = "Iosevka NF"
style = "Regular"

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.italic]
family = "Iosevka NF"
style = "Italic"

[font]
size = 12
